#!/bin/bash

# host ip is also used as the DNS server in WSL
host_ip=$(cat /etc/resolv.conf | grep "nameserver" | cut -f 2 -d " ")
# use clash
export HTTP_PROXY="http://$host_ip:7890"
export HTTPS_PROXY="http://$host_ip:7890"
export ALL_PROXY="socks5://$host_ip:7890"

# vim: ft=bash

