#!/usr/bin/env bash

# ====================
# debug
# ====================
# yabai -m config debug_output on

# ====================
# space setting
# ====================
# bsp or float (default: bsp)
yabai -m config layout bsp
# Set all padding and gaps to 20pt (default: 0)
yabai -m config top_padding    10
yabai -m config bottom_padding 10
yabai -m config left_padding   16
yabai -m config right_padding  16
yabai -m config window_gap     10

# Override spaces setting
yabai -m config --space 2 layout stack
yabai -m config --space 4 layout float

# ====================
# split ratios
# ====================
# Auto balance makes it so all windows always occupy the same space, independent of how deeply nested they are in the window tree. When a new window is inserted or a window is removed, the split ratios will be automatically adjusted
yabai -m config auto_balance on
yabai -m config split_ratio 0.5

# ====================
# Mouse support
# ====================
# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier fn

# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

# set mouse follows focus mode (default: off)
yabai -m config mouse_follows_focus on

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse off

# ====================
# Window modifications
# ====================
# New window spawns to the left if vertical split, or top if horizontal split
yabai -m config window_placement second_child

# floating windows are always on top (default: off)
yabai -m config window_topmost on

# modify window shadows (default: on, options: on, off, float)
# example: show shadows only for floating windows
yabai -m config window_shadow float

# window opacity (default: off)
yabai -m config window_opacity off
#yabai -m config active_window_opacity 1.0
# yabai -m config normal_window_opacity 0.9

# ====================
# border
# ====================
# Draw border for windows.
window_border on
# Width of window borders. If the given width is an odd number, it will be
# incremented by 1.
window_border_width 3
# Color of the border of the focused window.
# #7579e7 #b9fffc #ffa5a5
active_window_border_color 0xff7579e7
# Color of the border of an unfocused window.
normal_window_border_color 0xffb9fffc
# Color of the window --insert message selection.
insert_feedback_color 0xffffa5a5

# ====================
# App
# ====================
# rules
yabai -m rule --add app="^Chrome$" space=2
yabai -m rule --add app="^Mail$"   space=2
yabai -m rule --add app= "^System Preferences$"  manage=off
yabai -m rule --add app= "^DingTalk Lite$"  manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Stickies$" manage=off
