#!/usr/bin/env bash
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# see https://github.com/koekeishiya/yabai/wiki/Configuration
# ====================
# debug
# ====================
yabai -m config debug_output off

# ====================
# space setting
# ====================
# {{{
# bsp or float (default: bsp)
# bsp stands for
yabai -m config layout bsp
# Set all padding and gaps to 20pt (default: 0)
yabai -m config top_padding    12
yabai -m config bottom_padding 12
yabai -m config left_padding   12
yabai -m config right_padding  12
yabai -m config window_gap     12

# Override spaces setting
# yabai -m config --space 2 layout stack
# yabai -m config --space 4 layout float
# }}}

# ====================
# split ratios
# ====================
# Auto balance makes it so all windows always occupy the same space, independent of how deeply nested they are in the window tree. When a new window is inserted or a window is removed, the split ratios will be automatically adjusted
yabai -m config auto_balance off
# A value of 0.5 means that both old and new window occupy the same space; a value of 0.2 means that the old window occupies 20% of the available space and the new window occupies 80% of the available space.
yabai -m config split_ratio 0.5

# ====================
# Mouse support
# ====================
# {{{
# set mouse interaction modifier key (default: fn)
#mouse_modifier [cmd|alt|shift|ctrl|fn]
yabai -m config mouse_modifier alt

# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse autofocus

# set mouse follows focus mode (default: off)
yabai -m config mouse_follows_focus on

# }}}

# ====================
# Window modifications
# ====================
# {{{
# fist_child: New window spawns to the left if vertical split, or top if horizontal split
# second_child: New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# floating windows are always on top (default: off)
yabai -m config window_topmost off

# modify window shadows (default: on, options: on, off, float)
# example: show shadows only for floating windows
yabai -m config window_shadow float

# menubar_opacity
yabai -m config menubar_opacity 1.0

# window animation
# disable animation to reduce lag
yabai -m config window_animation_duration 0.0

# window opacity (default: off)
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9
# }}}

# ====================
# status_bar
# ====================
# {{{
# yabai -m config status_bar                   off
# yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
# yabai -m config status_bar_icon_font         "NerdFontJetBrains:Regular:12.0"
# yabai -m config status_bar_background_color  0xff202020
# yabai -m config status_bar_foreground_color  0xffa8a8a8
# yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
# yabai -m config status_bar_power_icon_strip   
# yabai -m config status_bar_space_icon        
# yabai -m config status_bar_clock_icon        
# }}}
# ====================
# App
# ====================
apps=(
  "Mail"
  "Books"
  "calibre"
  "E-book Viewer"
  "Reeder"
  "System Settings"
  "Music"
  "Finder"
  "Dictionary"
  "Stickies"
  "Android Studio"
  "DingTalk Lite"
  "WeChat"
  # screenshot
  "OBS"
  # Spotlight alternative
  "Raycast"
  # Microsoft Remote Desktop
  "Microsoft Remote Desktop"
  "Hammerspoon"
  "Karabiner-Elements"
  "Reeder"
  "Bruno"
  "DeepL"
  "Godot"
)

# disable management
for item in "${apps[@]}"; do
  yabai -m rule --add app="^${item}$" manage=off sub-layer=above
done

# --verbose to display
echo "yabai configuration loaded.."
# ====================
# JankyBorders
# ====================

borders_options=(
  active_color=0xff50fa7b
  inactive_color=0x0000000
  # background_color=0x302c2e34
  hidpi=on
  style=round
  width=6.0
)

# borders "${borders_options[@]}" &

# vim marker
