#!/usr/bin/env zsh
# Enable context menu in macOS system web view
# credit: https://blog.jim-nielsen.com/2022/inspecting-web-views-in-macos/
function __enable_context_menu() {
  defaults write NSGlobalDomain WebKitDeveloperExtras -bool true
  defaults write -g WebKitDeveloperExtras -bool YES
}

__enable_context_menu
