#!/usr/bin/env zsh

if [[ "$1" == "on" ]]; then
  # context menu
  # Enable context menu in macOS system web view
  # credit: https://blog.jim-nielsen.com/2022/inspecting-web-views-in-macos/
  defaults write NSGlobalDomain WebKitDeveloperExtras -bool true
  defaults write -g WebKitDeveloperExtras -bool YES
  # menubar debug icon
  defaults write -g _NS_4445425547 -bool true
  echo "Enabled mac debugging"
elif [[ "$1" == "off" ]]; then
  # Disable debugging
  unset __DEBUG_MAC
  defaults write NSGlobalDomain WebKitDeveloperExtras -bool false
  defaults write -g WebKitDeveloperExtras -bool NO
  defaults write -g _NS_4445425547 -bool false
  echo "Disabled mac debugging"
else
  echo "Usage: $0 <on|off>"
fi
