#!/usr/bin/env zsh
if ! [ -x "$(command -v brew)" ]; then
  echo "homebrew hasn't been installed yet"
  exit 1
else
  brew tap | grep 'wez/wezterm' &>/dev/null 2>&- || brew tap wez/wezterm
  brew upgrade --cask wezterm-nightly --no-quarantine --greedy-latest
fi
