#!/usr/bin/env zsh
cldjson(){
 local directory="build"
 if [[ -n $1 ]]; then
   echo "dir:" $1
   directory=$1
 fi
 local path="$(pwd)/${directory}"
 echo "path:" $path
 if [[ -d $path ]]; then
   # search in build
   if [[ -e $path/compile_commands.json ]]; then
     /usr/local/bin/gln -s $path/compile_commands.json compile_commands.json
     echo "find in $path and link!"
   else
     echo "Not found!"
   fi
 elif [[ -e compile_commands.json ]];then
   # link to parent directory
   /usr/local/bin/gln -s $(pwd)/compile_commands.json $(pwd)/../compile_commands.json
   echo "found in current dir and link!"
else
   echo "Not found!"
 fi
}

cldjson
