#!/usr/bin/env zsh

# help link CMake generated compile_commands.json in given directory to current pwd
# if directory is not given then try to link compile_commands.json in pwd to parent directory

function cldjson() {
 local directory="build"
 if [[ -n $1 ]]; then
   echo "dir:" $1
   directory=$1
 fi
 local path="$(pwd)/${directory}"
 echo "path:" $path
 if [[ -d $path ]]; then
   # search in build
   if [[ -e $path/compile_commands.json ]]; then
     /bin/ln -s $path/compile_commands.json compile_commands.json
     echo "find in $path and link!"
   else
     echo "Not found!"
   fi
 elif [[ -e compile_commands.json ]];then
   # link to parent directory
   /bin/ln -s $(pwd)/compile_commands.json $(pwd)/../compile_commands.json
   echo "found in current dir and link!"
else
   echo "Not found!"
 fi
}

cldjson "$@"
