#!/usr/bin/env zsh

function __clean_zwc() {
  setopt LOCAL_OPTIONS EXTENDED_GLOB

  local -a zwc_files old_files
  zwc_files=($(fd --hidden --no-ignore -e '.zwc'))
  old_files=($(fd --hidden --no-ignore -e '.old'))
  rm -i ${zwc_files[@]} ${old_files[@]}
}

__clean_zwc
