#!/usr/bin/env zsh
function __hostip() {
  if [ $SYSTEM = Darwin ];then
    ifconfig | rg 'inet ' | rg -Fv '127.0.0.1' | awk '{print $2}'
  else
    ip address | rg 'inet ' | rg -Fv '127.0.0.1' | awk '{print $2}'
  fi
}

__hostip
