.PHONY: ipython

ipython:
	-ln -s $(HOME)/.config/python/ipython/00-startup.py $(HOME)/.ipython/profile_default/startup/00-startup.py
	-ln -s $(HOME)/.config/python/ipython_config.py $(HOME)/.ipython/profile_default/ipython_config.py
