#!/usr/bin/env zsh

export ZSHDIR=$HOME/.config/zsh
# man 1 zmodules

######################
# Options
######################
# zsh default options
# emulate -lLR zsh
# {{{

setopt CORRECT
#setopt CORRECT_ALL
setopt auto_cd # automatic cd to a directory without leading cd
setopt multios
setopt prompt_subst
zstyle ':completion:*' rehash true # refresh autocompletion

## History wrapper
function slim_zsh_history {
  local clear list
  zparseopts -E c=clear l=list

  if [[ -n "$clear" ]]; then
    # if -c provided, clobber the history file
    echo -n >| "$HISTFILE"
    echo >&2 History file deleted. Reload the session to see its effects.
  elif [[ -n "$list" ]]; then
    # if -l provided, run as if calling `fc' directly
    builtin fc "$@"
  else
    # unless a number is provided, show all history events (starting from 1)
    [[ ${@[-1]-} = *[0-9]* ]] && builtin fc -l "$@" || builtin fc -l "$@" 1
  fi
}

# Timestamp format
case ${HIST_STAMPS-} in
  "mm/dd/yyyy") alias history='slim_zsh_history -f' ;;
  "dd.mm.yyyy") alias history='slim_zsh_history -E' ;;
  "yyyy-mm-dd") alias history='slim_zsh_history -i' ;;
  "") alias history='slim_zsh_history' ;;
  *) alias history="slim_zsh_history -t '$HIST_STAMPS'" ;;
esac

## History file configuration {{{
[ -z "$HISTFILE" ] && HISTFILE="$HOME/.zsh_history"
[ "$HISTSIZE" -lt 50000 ] && HISTSIZE=50000
[ "$SAVEHIST" -lt 10000 ] && SAVEHIST=10000

## History command configuration
setopt extended_history       # record timestamp and elapsed time of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_reduce_blanks     # remove blank lines from history list
setopt hist_find_no_dups      # ignore duplicates when searching
setopt hist_verify            # show command with history expansion to user before running it
setopt share_history          # share command history data across zsh sessions
setopt append_history         # append to history rather than overwrite
# setopt inc_append_history # adds commands while typing commands instead of at shell exit.

# use CTRL-R to search command history reversely 
bindkey -v
bindkey '^R' history-incremental-search-backward
# }}}

# enable diff color if possible.
if command diff --color . . &>/dev/null; then
  alias diff='diff --color'
fi
# }}}

######################
# zsh functions
######################
#{{{
autoload -Uz compinit && compinit
#}}}

######################
# plugins 
######################
# could get some ideas from famous Zsh frameworks
# {{{
source ~/.config/zsh/vendor/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.config/zsh/vendor/zsh-autosuggestions/zsh-autosuggestions.zsh

# lazy load functions
# insert at head
fpath=(~/.config/zsh/funcs "${fpath[@]}") 
autoload -Uz $fpath[1]/*(.:t)

## plugins
for file in ~/.config/zsh/plugins/*.zsh; do
  source "$file"
done

#source ~/.config/zsh/plugins/vi-mode.zsh
#source ~/.config/zsh/plugins/dirs.zsh
#source ~/.config/zsh/plugins/extract.zsh
#source ~/.config/zsh/plugins/aliases.zsh
#source ~/dev/grepo_shell/fzf-tab/fzf-tab.plugin.zsh
#source ~/.config/zsh/fzf-tab-config.zsh
#source ~/.config/zsh/plugins/yogit.plugin.zsh
#source ~/.config/zsh/plugins/utils.plugin.zsh

# debug
#export _ZL_ECHO=1
#export _ZL_LOG_NAME=true
# eval "$(lua ~/.config/zsh/vendor/z.lua --init zsh enhanced)"
# }}}

# vim:ft=zsh ts=2 sw=2 sts=2 et fenc=utf-8
