# see https://developers.openai.com/codex/local-config#cli
# read-only | workspace-write | danger-full-access
sandbox_mode = "danger-full-access"
approval_policy = "never"
tool_output_token_limit = 25000
model_auto_compact_token_limit = 233000
personality = "pragmatic"
web_search = "live"

model = "gpt-5.3-codex"
preferred_auth_method = "chatgpt" # chatgpt/apikey

model_reasoning_effort = "xhigh"
model_reasoning_summary = "detailed"



#model_provider = "openrouter"
#profile = "openrouter"

[profiles.openrouter]
model = "openai/gpt-5.3-codex"

[features]
rmcp_client = true
skills = true
skill_snapshot = true
apply_patch_freeform = false
ghost_commit = false
unified_exec = true
shell_snapshot = true
steer = true
multi_agent = true
# responses_websockets_v2 = true

[mcp_servers.nowledge-mem]
url = "http://127.0.0.1:14242/mcp/"
startup_timeout_sec = 30
tool_timeout_sec = 45

[mcp_servers.nowledge-mem.http_headers]
APP = "Codex"

[projects."/Users/tizee/projects/project-conf/dotfiles/tizee-dotfiles"]
trust_level = "untrusted"

[tui]
status_line = ["model-with-reasoning", "five-hour-limit", "weekly-limit", "project-root", "git-branch", "context-remaining", "context-used", "context-window-size"]

[model_providers.anyrouter]
name = "Any Router"
base_url = "https://anyrouter.top/v1"
wire_api = "responses"

[model_providers.cloud]
name = "cloud"
base_url = "https://chat.cloudapi.vip/v1"
wire_api = "responses"

[model_providers.openrouter]
name = "OpenRouter"
base_url = "https://openrouter.ai/api/v1"
env_key = "OPENROUTER_API_KEY"
wire_api = "responses"
# wire_api = "chat"
experimental_use_freeform_apply_patch = false
include_apply_patch_tool = false

[model_providers.openai]
name = "OpenAI"
base_url = "https://api.openai.com/v1"
env_key = "OPENAI_API_KEY"
wire_api = "responses"
