name: ci
env:
  CONFIG_DIR_NAME: test_config
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
      - cron: '0 0 * * 0'
jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Create fake .config
        run: mkdir $HOME/$CONFIG_DIR_NAME
      - name: install
        run: make install
      - name: zsh
        run: make zshforce
      - name: nvim
        run: make nvimforce
      - name: emacs
        run: make zshforce
      - name: uninstall
        run: make uninstall
